In [1]:
import pandas as pd
df = pd.read_excel("Final Project Data Set.xlsx", sheet_name="Patient History")
df.head(10)

,Zone,Measurement.Att.Date,Gender,Race,StaffEducation,Weight,Height,BMI,HeartAttack,Stroke,...,OccupationType,Healthy,Habits,Diabetes2,BloodPressure,Cholesterol,Overweight,AgeGrp,scnZone,healthRisk
0,ZoneA_Date1,1,Female,Malay,8.Others,58.2,1.51,25.5,No,No,...,Unemployed,Healthy,Negative Habits,NaN,NaN,NaN,Female Overweight,60-69,ZoneA,normal
1,ZoneA_Date1,1,Male,Chinese,8.Others,75.9,1.68,26.9,No,No,...,Others,Healthy,Negative Habits,NaN,NaN,NaN,Male Overweight,60-69,ZoneA,normal
2,ZoneA_Date1,1,Female,Chinese,8.Others,50.3,1.46,23.6,Yes,No,...,Blue-collar Job,Unhealthy,Negative Habits,NaN,Above Cutoff,HighCho,Female Overweight,60-69,ZoneA,normal
3,ZoneA_Date1,1,Female,Indian,8.Others,76.9,1.72,26.0,No,No,...,White-collar Job,Unhealthy,Negative Habits,NaN,NaN,HighCho,Female Overweight,60-69,ZoneA,normal
4,ZoneA_Date1,1,Male,Indian,8.Others,42.1,1.67,15.1,No,No,...,Others,Healthy,Negative Habits,NaN,NaN,NaN,Male Not Overweight,60-69,ZoneA,normal
5,ZoneA_Date1,1,Male,Chinese,8.Others,91.1,1.77,29.1,No,No,...,Unemployed,Unhealthy,Negative Habits,NaN,Above Cutoff,NaN,Male Overweight,60-69,ZoneA,moderate high
6,ZoneA_Date1,1,Male,Chinese,8.Others,61.5,1.60,24.0,No,No,...,NaN,Unhealthy,Negative Habits,NaN,NaN,HighCho,Male Overweight,60-69,ZoneA,normal
7,ZoneA_Date1,1,Female,Chinese,8.Others,56.7,1.58,22.7,No,No,...,Unemployed,Unhealthy,Negative Habits,Above Cutoff,Above Cutoff,NaN,Female Not Overweight,60-69,ZoneA,high
8,ZoneA_Date1,1,Female,Chinese,8.Others,55.8,1.47,25.8,No,No,...,Unemployed,Unhealthy,Negative Habits,NaN,Above Cutoff,HighCho,Female Overweight,70+,ZoneA,moderate high
9,ZoneA_Date1,1,Female,Chinese,8.Others,51.4,1.49,23.1,No,No,...,Others,Healthy,Negative Habits,NaN,NaN,NaN,Female Overweight,70+,ZoneA,normal

In [2]:
df.shape

(5191, 30)

In [3]:
df.columns

Index(['Zone', 'Measurement.Att.Date', 'Gender', 'Race', 'StaffEducation',
       'Weight', 'Height', 'BMI', 'HeartAttack', 'Stroke', 'Diabetes', 'HBP',
       'HBldChol', 'Smoking', 'Exercise', 'Stress', 'Health', 'FruitsVeg',
       'DiabetesFoot', 'PreferredLanguage', 'OccupationType', 'Healthy',
       'Habits', 'Diabetes2', 'BloodPressure', 'Cholesterol', 'Overweight',
       'AgeGrp', 'scnZone', 'healthRisk'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5191 entries, 0 to 5190
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Zone                  5191 non-null   object
 1   Measurement.Att.Date  5191 non-null   int64
 2   Gender                5191 non-null   object
 3   Race                  5191 non-null   object
 4   StaffEducation        4964 non-null   object
 5   Weight                5182 non-null   float64
 6   Height                5181 non-null   float64
 7   BMI                   5181 non-null   float64
 8   HeartAttack           5191 non-null   object
 9   Stroke                5191 non-null   object
 10  Diabetes              5191 non-null   object
 11  HBP                   5191 non-null   object
 12  HBldChol              5191 non-null   object
 13  Smoking               5191 non-null   object
 14  Exercise              5191 non-null   object
 15  Stress                5191 non-null   object
 16  Health                5029 non-null   object
 17  FruitsVeg             5191 non-null   object
 18  DiabetesFoot          303 non-null    object
 19  PreferredLanguage     5191 non-null   object
 20  OccupationType        4853 non-null   object
 21  Healthy               5191 non-null   object
 22  Habits                5191 non-null   object
 23  Diabetes2             940 non-null    object
 24  BloodPressure         2073 non-null   object
 25  Cholesterol           3026 non-null   object
 26  Overweight            5191 non-null   object
 27  AgeGrp                5191 non-null   object
 28  scnZone               5191 non-null   object
 29  healthRisk            5163 non-null   object
dtypes: float64(3), int64(1), object(26)
memory usage: 1.2+ MB

In [5]:
df.describe()

       Measurement.Att.Date       Weight       Height         BMI
count           5191.000000  5182.000000  5181.000000  5181.00000
mean              18.899441    62.856523     1.610992    24.16076
std               10.336958    12.619709     0.085232     4.19060
min                1.000000    29.300000     1.310000    12.70000
25%               10.000000    53.925000     1.550000    21.40000
50%               19.000000    61.450000     1.610000    23.70000
75%               27.000000    70.300000     1.670000    26.40000
max               38.000000   182.000000     1.960000    61.50000

In [37]:
# Missing Values
df.isnull().sum()

Zone                       0
Measurement.Att.Date       0
Gender                     0
Race                       0
StaffEducation           227
Weight                     9
Height                    10
BMI                       10
HeartAttack                0
Stroke                     0
Diabetes                   0
HBP                        0
HBldChol                   0
Smoking                    0
Exercise                   0
Stress                     0
Health                   162
FruitsVeg                  0
DiabetesFoot            4888
PreferredLanguage          0
OccupationType           338
Healthy                    0
Habits                     0
Diabetes2               4251
BloodPressure           3118
Cholesterol             2165
Overweight                 0
AgeGrp                     0
scnZone                    0
healthRisk                28
dtype: int64

In [38]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage[missing_percentage > 0].sort_values(ascending=False)

DiabetesFoot      94.162974
Diabetes2         81.891736
BloodPressure     60.065498
Cholesterol       41.706800
OccupationType     6.511270
StaffEducation     4.372953
Health             3.120786
healthRisk         0.539395
Height             0.192641
BMI                0.192641
Weight             0.173377
dtype: float64

In [39]:
df["DiabetesFoot"].value_counts(dropna=False)

DiabetesFoot
NaN    4888
Yes     156
No      147
Name: count, dtype: int64

In [40]:
df["Diabetes2"].value_counts(dropna=False)

Diabetes2
NaN             4251
Above Cutoff     940
Name: count, dtype: int64

In [41]:
df["BloodPressure"].value_counts(dropna=False)

BloodPressure
NaN             3118
Above Cutoff    2073
Name: count, dtype: int64

In [42]:
df["Cholesterol"].value_counts(dropna=False)

Cholesterol
HighCho     3026
NaN         2165
Name: count, dtype: int64

In [43]:
df["Diabetes"].value_counts(dropna=False)

Diabetes
No     4774
Yes     417
Name: count, dtype: int64

In [44]:
df["HBP"].value_counts(dropna=False)

HBP
No     4083
Yes    1108
Name: count, dtype: int64

In [45]:
df["HBldChol"].value_counts(dropna=False)

HBldChol
No     3675
Yes    1516
Name: count, dtype: int64

In [46]:
df["Health"].value_counts(dropna=False)

Health
Good        3839
VeryGood     733
NotGood      443
NaN          162
Poor          14
Name: count, dtype: int64

In [47]:
df.dtypes

Zone                     object
Measurement.Att.Date      int64
Gender                   object
Race                     object
StaffEducation           object
Weight                  float64
Height                  float64
BMI                     float64
HeartAttack              object
Stroke                   object
Diabetes                 object
HBP                      object
HBldChol                 object
Smoking                  object
Exercise                 object
Stress                   object
Health                   object
FruitsVeg                object
DiabetesFoot             object
PreferredLanguage        object
OccupationType           object
Healthy                  object
Habits                   object
Diabetes2                object
BloodPressure            object
Cholesterol              object
Overweight               object
AgeGrp                   object
scnZone                  object
healthRisk               object
dtype: object

In [48]:
df["Gender"].value_counts(dropna=False)

Gender
Female    3025
Male      2166
Name: count, dtype: int64

In [49]:
df["Race"].value_counts(dropna=False)

Race
Chinese    4049
Malay       608
Indian      405
Others      129
Name: count, dtype: int64

In [50]:
df["StaffEducation"].value_counts(dropna=False)

StaffEducation
2.Primary/PSLE           1416
3.GCE O/N LevelE         1396
8.Others                  585
7.Degree/Professional     444
5.Diploma                 437
1.No Formal Education     381
NaN                       227
6.GCE A Level             157
4.NTC 2/3                 148
Name: count, dtype: int64

In [51]:
df["Smoking"].value_counts(dropna=False)

Smoking
No     4632
Yes     559
Name: count, dtype: int64

In [52]:
df["Zone"].value_counts(dropna=False)

Zone
ZoneA_Date14    325
ZoneA_Date17    278
ZoneB_Date25    247
ZoneA_Date15    217
ZoneB_Date27    212
ZoneA_Date18    211
ZoneA_Date26    186
ZoneA_Date20    182
ZoneA_Date5     178
ZoneA_Date31    174
ZoneA_Date4     173
ZoneA_Date1     162
ZoneA_Date21    158
ZoneA_Date7     152
ZoneA_Date32    129
ZoneA_Date2     125
ZoneA_Date27    119
ZoneA_Date38    115
ZoneB_Date29    110
ZoneA_Date30    107
ZoneA_Date9     105
ZoneA_Date35    104
ZoneB_Date22     94
ZoneB_Date24     94
ZoneB_Date19     91
ZoneA_Date12     91
ZoneB_Date8      89
ZoneA_Date28     89
ZoneB_Date10     85
ZoneB_Date31     84
ZoneB_Date33     80
ZoneB_Date5      79
ZoneA_Date13     78
ZoneB_Date16     68
ZoneB_Date6      66
ZoneA_Date36     65
ZoneB_Date37     61
ZoneB_Date23     58
ZoneB_Date3      54
ZoneB_Date2      52
ZoneB_Date34     40
ZoneB_Date11      4
Name: count, dtype: int64

In [53]:
print(df.columns.tolist())

['Zone', 'Measurement.Att.Date', 'Gender', 'Race', 'StaffEducation', 'Weight', 'Height', 'BMI', 'HeartAttack', 'Stroke', 'Diabetes', 'HBP', 'HBldChol', 'Smoking', 'Exercise', 'Stress', 'Health', 'FruitsVeg', 'DiabetesFoot', 'PreferredLanguage', 'OccupationType', 'Healthy', 'Habits', 'Diabetes2', 'BloodPressure', 'Cholesterol', 'Overweight', 'AgeGrp', 'scnZone', 'healthRisk']

In [54]:
df["Exercise"].value_counts(dropna=False)

Exercise
<30     2352
30       842
60       757
150+     714
120      307
90       219
Name: count, dtype: int64

In [55]:
df["Stress"].value_counts(dropna=False)

Stress
FairlyWell     3179
VeryWell       1883
HaveTrouble     129
Name: count, dtype: int64

In [56]:
df["HeartAttack"].value_counts(dropna=False)

HeartAttack
No     5049
Yes     142
Name: count, dtype: int64

In [57]:
df["Stroke"].value_counts(dropna=False)

Stroke
No     5101
Yes      90
Name: count, dtype: int64

In [58]:
df["FruitsVeg"].value_counts(dropna=False)

FruitsVeg
2Serve      2133
1Serve      1821
3orMore     1111
NotAtAll     126
Name: count, dtype: int64

In [59]:
df["PreferredLanguage"].value_counts(dropna=False)

PreferredLanguage
English    3112
Chinese    1899
Malay       180
Name: count, dtype: int64

In [60]:
columns_to_check = [
    "OccupationType",
    "Healthy",
    "Habits",
    "Diabetes2",
    "BloodPressure",
    "Cholesterol",
    "Overweight",
    "AgeGrp",
    "scnZone",
    "healthRisk",
    "DiabetesFoot"
]
for col in columns_to_check:
    print("\n" + "="*50)
    print(col)
    print("="*50)
    print(df[col].value_counts(dropna=False))

==================================================
OccupationType
==================================================
OccupationType
Unemployed          1985
Blue-collar Job     1850
White-collar Job     914
NaN                  338
Others               104
Name: count, dtype: int64

==================================================
Healthy
==================================================
Healthy
Unhealthy    3881
Healthy      1310
Name: count, dtype: int64

==================================================
Habits
==================================================
Habits
Negative Habits    4441
Positive Habits     750
Name: count, dtype: int64

==================================================
Diabetes2
==================================================
Diabetes2
NaN             4251
Above Cutoff     940
Name: count, dtype: int64

==================================================
BloodPressure
==================================================
BloodPressure
NaN             3118
Above Cutoff    2073
Name: count, dtype: int64

==================================================
Cholesterol
==================================================
Cholesterol
HighCho     3026
NaN         2165
Name: count, dtype: int64

==================================================
Overweight
==================================================
Overweight
Female Overweight        1616
Female Not Overweight    1409
Male Overweight          1373
Male Not Overweight       793
Name: count, dtype: int64

==================================================
AgeGrp
==================================================
AgeGrp
50-59    1815
40-49    1684
60-69    1091
70+       576
<40        25
Name: count, dtype: int64

==================================================
scnZone
==================================================
scnZone
ZoneA    3523
ZoneB    1668
Name: count, dtype: int64

==================================================
healthRisk
==================================================
healthRisk
normal           3085
moderate high    1587
high              384
critical          107
NaN                28
Name: count, dtype: int64

==================================================
DiabetesFoot
==================================================
DiabetesFoot
NaN    4888
Yes     156
No      147
Name: count, dtype: int64

In [61]:
numeric_columns = ["Weight", "Height", "BMI", "Measurement.Att.Date"]
for col in numeric_columns:
    print("\n" + "="*50)
    print(col)
    print("="*50)
    print("Missing:", df[col].isnull().sum())
    print("Unique values:", df[col].nunique())
    if col != "Measurement.Att.Date":
        print(df[col].describe())
    else:
        print("Minimum:", df[col].min())
        print("Maximum:", df[col].max())
        print("First 20 values:")
        print(df[col].head(20).tolist())

==================================================
Weight
==================================================
Missing: 9
Unique values: 599
count    5182.000000
mean       62.856523
std        12.619709
min        29.300000
25%        53.925000
50%        61.450000
75%        70.300000
max       182.000000
Name: Weight, dtype: float64

==================================================
Height
==================================================
Missing: 10
Unique values: 55
count    5181.000000
mean        1.610992
std         0.085232
min         1.310000
25%         1.550000
50%         1.610000
75%         1.670000
max         1.960000
Name: Height, dtype: float64

==================================================
BMI
==================================================
Missing: 10
Unique values: 261
count    5181.00000
mean       24.16076
std         4.19060
min        12.70000
25%        21.40000
50%        23.70000
75%        26.40000
max        61.50000
Name: BMI, dtype: float64

==================================================
Measurement.Att.Date
==================================================
Missing: 0
Unique values: 38
Minimum: 1
Maximum: 38
First 20 values:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [62]:
# Duplicates
df.duplicated().sum()

np.int64(0)

In [63]:
# Outliers
numeric_cols = ["Weight", "Height", "BMI"]
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print("\n" + "="*50)
    print(col)
    print("="*50)
    print("Lower bound:", lower)
    print("Upper bound:", upper)
    print("Number of outliers:", len(outliers))
    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())

==================================================
Weight
==================================================
Lower bound: 29.362499999999997
Upper bound: 94.8625
Number of outliers: 69
Minimum: 29.3
Maximum: 182.0

==================================================
Height
==================================================
Lower bound: 1.37
Upper bound: 1.8499999999999996
Number of outliers: 11
Minimum: 1.31
Maximum: 1.96

==================================================
BMI
==================================================
Lower bound: 13.899999999999999
Upper bound: 33.9
Number of outliers: 128
Minimum: 12.7
Maximum: 61.5

In [66]:
# Checking actual Outlier Records
for col in ["Weight", "Height", "BMI"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    print("\n", col, "OUTLIERS")
    print(df[(df[col] < lower) | (df[col] > upper)][[col]].head(20))

 Weight OUTLIERS
      Weight
46     105.9
54     111.8
129     99.1
139     99.6
270    120.9
311    102.2
323    114.2
446    103.6
485     97.3
539     95.4
665     95.6
696    104.4
711     95.8
788     29.3
808    121.5
966    104.3
1040    95.8
1112    96.7
1159   100.9
1316    95.5

 Height OUTLIERS
      Height
91      1.95
393     1.87
658     1.96
683     1.85
1220    1.88
1493    1.87
1542    1.31
1732    1.85
2239    1.85
3528    1.35
4550    1.87

 BMI OUTLIERS
      BMI
46   34.2
54   37.8
108  34.4
129  45.2
139  36.1
211  35.5
270  38.2
311  38.5
323  36.9
362  35.2
422  35.7
436  36.0
450  35.0
475  37.3
485  43.2
595  34.8
612  34.7
635  40.6
653  42.8
660  39.4

In [67]:
# Check wheather BMI is consistent with Height and Weight
df["BMI_calculated"] = (
    df["Weight"] / (df["Height"] ** 2)
).round(1)
df["BMI_difference"] = (
    df["BMI"] - df["BMI_calculated"]
).abs()
df[["Weight", "Height", "BMI", "BMI_calculated", "BMI_difference"]].head(10)

   Weight  Height   BMI  BMI_calculated  BMI_difference
0    58.2    1.51  25.5            25.5             0.0
1    75.9    1.68  26.9            26.9             0.0
2    50.3    1.46  23.6            23.6             0.0
3    76.9    1.72  26.0            26.0             0.0
4    42.1    1.67  15.1            15.1             0.0
5    91.1    1.77  29.1            29.1             0.0
6    61.5    1.60  24.0            24.0             0.0
7    56.7    1.58  22.7            22.7             0.0
8    55.8    1.47  25.8            25.8             0.0
9    51.4    1.49  23.1            23.2             0.1

In [68]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [70]:
# Tells us Affected rows
df[df[["Weight", "Height", "BMI"]].isnull().any(axis=1)][
    ["Weight", "Height", "BMI"]
].to_string()

'      Weight  Height  BMI\n22       NaN     NaN  NaN\n64       NaN     NaN  NaN\n349      NaN     NaN  NaN\n1992     NaN     NaN  NaN\n2066     NaN     NaN  NaN\n2160     NaN     NaN  NaN\n2504     NaN     NaN  NaN\n2616    59.1     NaN  NaN\n3486     NaN     NaN  NaN\n4867     NaN     NaN  NaN'

In [72]:
# Filling the missing values
df["Weight"] = df["Weight"].fillna(df["Weight"].median())
df["Height"] = df["Height"].fillna(df["Height"].median())
df["BMI"] = df["BMI"].fillna(df["BMI"].median())

In [73]:
# Filling Categorical Missing Values
categorical_cols = [
    "DiabetesFoot",
    "Diabetes2",
    "BloodPressure",
    "Cholesterol",
    "OccupationType",
    "StaffEducation",
    "Health",
    "healthRisk"
]
for col in categorical_cols:
    df[col] = df[col].fillna("Not Recorded")

In [74]:
# Rechecking all missing values
print("Remaining missing values:")
print(df.isnull().sum())

Remaining missing values:
Zone                     0
Measurement.Att.Date     0
Gender                   0
Race                     0
StaffEducation           0
Weight                   0
Height                   0
BMI                      0
HeartAttack              0
Stroke                   0
Diabetes                 0
HBP                      0
HBldChol                 0
Smoking                  0
Exercise                 0
Stress                   0
Health                   0
FruitsVeg                0
DiabetesFoot             0
PreferredLanguage        0
OccupationType           0
Healthy                  0
Habits                   0
Diabetes2                0
BloodPressure            0
Cholesterol              0
Overweight               0
AgeGrp                   0
scnZone                  0
healthRisk               0
BMI_calculated          10
BMI_difference          10
dtype: int64

In [75]:
df.drop(
    columns=["BMI_calculated", "BMI_difference"],
    inplace=True
)
print(df.columns.tolist())

['Zone', 'Measurement.Att.Date', 'Gender', 'Race', 'StaffEducation', 'Weight', 'Height', 'BMI', 'HeartAttack', 'Stroke', 'Diabetes', 'HBP', 'HBldChol', 'Smoking', 'Exercise', 'Stress', 'Health', 'FruitsVeg', 'DiabetesFoot', 'PreferredLanguage', 'OccupationType', 'Healthy', 'Habits', 'Diabetes2', 'BloodPressure', 'Cholesterol', 'Overweight', 'AgeGrp', 'scnZone', 'healthRisk']

In [76]:
print(df.isnull().sum())

Zone                    0
Measurement.Att.Date    0
Gender                  0
Race                    0
StaffEducation          0
Weight                  0
Height                  0
BMI                     0
HeartAttack             0
Stroke                  0
Diabetes                0
HBP                     0
HBldChol                0
Smoking                 0
Exercise                0
Stress                  0
Health                  0
FruitsVeg               0
DiabetesFoot            0
PreferredLanguage       0
OccupationType          0
Healthy                 0
Habits                  0
Diabetes2               0
BloodPressure           0
Cholesterol             0
Overweight              0
AgeGrp                  0
scnZone                 0
healthRisk              0
dtype: int64

In [77]:
# Final Data Quality Verification
print("========== FINAL DATA QUALITY CHECK ==========")
print("\n1. Dataset Shape:")
print(df.shape)
print("\n2. Duplicate Rows:")
print(df.duplicated().sum())
print("\n3. Missing Values:")
print(df.isnull().sum())
print("\n4. Data Types:")
print(df.dtypes)
print("\n5. Numerical Summary:")
print(df[["Weight", "Height", "BMI"]].describe())
print("\n6. Categorical Columns:")
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}:")
    print(df[col].unique())

========== FINAL DATA QUALITY CHECK ==========

1. Dataset Shape:
(5191, 30)

2. Duplicate Rows:
0

3. Missing Values:
Zone                    0
Measurement.Att.Date    0
Gender                  0
Race                    0
StaffEducation          0
Weight                  0
Height                  0
BMI                     0
HeartAttack             0
Stroke                  0
Diabetes                0
HBP                     0
HBldChol                0
Smoking                 0
Exercise                0
Stress                  0
Health                  0
FruitsVeg               0
DiabetesFoot            0
PreferredLanguage       0
OccupationType          0
Healthy                 0
Habits                  0
Diabetes2               0
BloodPressure           0
Cholesterol             0
Overweight              0
AgeGrp                  0
scnZone                 0
healthRisk              0
dtype: int64

4. Data Types:
Zone                     object
Measurement.Att.Date      int64
Gender                   object
Race                     object
StaffEducation           object
Weight                  float64
Height                  float64
BMI                     float64
HeartAttack              object
Stroke                   object
Diabetes                 object
HBP                      object
HBldChol                 object
Smoking                  object
Exercise                 object
Stress                   object
Health                   object
FruitsVeg                object
DiabetesFoot             object
PreferredLanguage        object
OccupationType           object
Healthy                  object
Habits                   object
Diabetes2                object
BloodPressure            object
Cholesterol              object
Overweight               object
AgeGrp                   object
scnZone                  object
healthRisk               object
dtype: object

5. Numerical Summary:
            Weight      Height          BMI
count  5191.000000  5191.00000  5191.000000
mean     62.854084     1.61099    24.159873
std      12.608898     0.08515     4.186609
min      29.300000     1.31000    12.700000
25%      54.000000     1.55000    21.400000
50%      61.450000     1.61000    23.700000
75%      70.200000     1.67000    26.400000
max     182.000000     1.96000    61.500000

6. Categorical Columns:

Zone:
['ZoneA_Date1' 'ZoneA_Date2' 'ZoneB_Date2' 'ZoneB_Date3' 'ZoneA_Date4'
 'ZoneA_Date5' 'ZoneB_Date5' 'ZoneB_Date6' 'ZoneA_Date7' 'ZoneB_Date8'
 'ZoneA_Date9' 'ZoneB_Date10' 'ZoneB_Date11' 'ZoneA_Date12' 'ZoneA_Date13'
 'ZoneA_Date14' 'ZoneA_Date15' 'ZoneB_Date16' 'ZoneA_Date17'
 'ZoneA_Date18' 'ZoneB_Date19' 'ZoneA_Date20' 'ZoneA_Date21'
 'ZoneB_Date22' 'ZoneB_Date23' 'ZoneB_Date24' 'ZoneB_Date25'
 'ZoneA_Date26' 'ZoneA_Date27' 'ZoneB_Date27' 'ZoneA_Date28'
 'ZoneB_Date29' 'ZoneA_Date30' 'ZoneA_Date31' 'ZoneB_Date31'
 'ZoneA_Date32' 'ZoneB_Date33' 'ZoneB_Date34' 'ZoneA_Date35'
 'ZoneA_Date36' 'ZoneB_Date37' 'ZoneA_Date38']

Gender:
['Female' 'Male']

Race:
['Malay' 'Chinese' 'Indian' 'Others']

StaffEducation:
['8.Others' '7.Degree/Professional' '5.Diploma' 'Not Recorded'
 '3.GCE O/N LevelE' '2.Primary/PSLE' '4.NTC 2/3' '1.No Formal Education'
 '6.GCE A Level']

HeartAttack:
['No' 'Yes']

Stroke:
['No' 'Yes']

Diabetes:
['No' 'Yes']

HBP:
['No' 'Yes']

HBldChol:
['No' 'Yes']

Smoking:
['No' 'Yes']

Exercise:
['<30' 30 '150+' 60 120 90]

Stress:
['FairlyWell' 'VeryWell' 'HaveTrouble']

Health:
['Not Recorded' 'VeryGood' 'Good' 'NotGood' 'Poor']

FruitsVeg:
['2Serve' '3orMore' '1Serve' 'NotAtAll']

DiabetesFoot:
['Not Recorded' 'Yes' 'No']

PreferredLanguage:
['Malay' 'Chinese' 'English']

OccupationType:
['Unemployed' 'Others' 'Blue-collar Job' 'White-collar Job' 'Not Recorded']

Healthy:
['Healthy' 'Unhealthy']

Habits:
['Negative Habits' 'Positive Habits']

Diabetes2:
['Not Recorded' 'Above Cutoff']

BloodPressure:
['Not Recorded' 'Above Cutoff']

Cholesterol:
['Not Recorded' 'HighCho ']

Overweight:
['Female Overweight' 'Male Overweight' 'Male Not Overweight'
 'Female Not Overweight']

AgeGrp:
['60-69' '70+' '50-59' '40-49' '<40']

scnZone:
['ZoneA' 'ZoneB']

healthRisk:
['normal' 'moderate high' 'high' 'critical' 'Not Recorded']

In [78]:
df.to_excel("Diagnosis_Data_Cleaned.xlsx", index=False)

In [79]:
import os
print(os.path.exists("Diagnosis_Data_Cleaned.xlsx"))

True